wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 8080:80

db:
  image: mariadb
  volumes:
      - ./maribaDB:/var/lib/mysql
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=azpay
      - MYSQL_PASSWORD=azpay123
      - MYSQL_DATABASE=db
