version: '3'
services:
  wordpress:
    image: l2go/woocommerce:latest
    ports:
      - 8189:80
    environment:
      - WORDPRESS_WP_DEBUG="false"
      - WORDPRESS_DB_HOST=127.0.0.1
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_PORT=3306